### PR TITLE
Add CI for pulling charts from GH releases

### PR DESCRIPTION
**Pull request by indyfree**
Towards https://github.com/giantswarm/giantswarm/issues/4848.
Dependend on https://github.com/giantswarm/prometheus/pull/112.

Adds CI that publishes charts to the the hosted helm repostiory (https://giantswarm.github.io/app-catalog/). The chart tarballs are pulled from GH releases from apps that are specified in the `APP` file.

- The `ci-scripts/build-repo.sh` is based on the upstream CI script: https://github.com/helm/charts/blob/master/test/repo-sync.sh
(Do we need to include APACHE licencse here too then btw?)
- You can read up about the upstream helm repositories wer are using here: https://github.com/helm/helm/blob/master/docs/chart_repository.md
- TL;DR: The helm charts are hosted on this repo, which is published with GitHub Pages

Notes:
- This script-based solution is to have a first working app-catalog out there soon. Considerations about moving it to either GitHub Actions, CircleCI Orbs or integrate into our tooling (e.g. architect, devctl) should be taken in the future.
- **Caution:** The Circle Cronjob is set up to run every 15 Minutes. If multiple versions of one App are relased within the 15 minute interval, only the latest will get published. We should consider changing this in the future.

### CODE REVIEW

**Comment by indyfree** [comment]
When https://github.com/giantswarm/prometheus/pull/112 is merged and a tag got pushed, a release will be published.
When a prom release is published,we need to rerun, which currently fails (correctly) with
`No GitHub release of 'giantswarm/prometheus' found!`

**Comment by indyfree** [comment]
Edit: Assigned to ross too, since I am leaving. Probably sig-releng should get on the boat here too.

**Comment by rossf7** [comment]
Ack. Thanks @indyfree!

**Comment by indyfree** [comment]
This PR got accidentally merged. I resetted and opened this one again: https://github.com/giantswarm/app-catalog/pull/2

**Pull request merged**
